/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author T-Gamer
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIniciarQuiz = new javax.swing.JButton();
        rdbCS = new javax.swing.JRadioButton();
        rdbCR7 = new javax.swing.JRadioButton();
        rdbLOL = new javax.swing.JRadioButton();
        rdbMATEMATICA = new javax.swing.JRadioButton();
        rdbSUPERNATURAL = new javax.swing.JRadioButton();
        rdbNARUTO = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("VeryQuizz");

        jLabel2.setText("Teste seu conhecimento nos quizes abaixo!");

        btnIniciarQuiz.setText("Iniciar Quiz");
        btnIniciarQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarQuizActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbCS);
        rdbCS.setText("Quiz do Counter Strike");
        rdbCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCSActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbCR7);
        rdbCR7.setText("Quiz do Cristiano Ronaldo");
        rdbCR7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCR7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbLOL);
        rdbLOL.setText("Quiz do League of Legends");

        buttonGroup1.add(rdbMATEMATICA);
        rdbMATEMATICA.setText("Quiz de matemática");

        buttonGroup1.add(rdbSUPERNATURAL);
        rdbSUPERNATURAL.setText("Quiz de Supernatural");

        buttonGroup1.add(rdbNARUTO);
        rdbNARUTO.setText("Quiz de Naruto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniciarQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rdbCS)
                        .addGap(255, 255, 255))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbLOL)
                                    .addComponent(rdbSUPERNATURAL))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbNARUTO)
                                    .addComponent(rdbMATEMATICA)
                                    .addComponent(rdbCR7))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbCS)
                    .addComponent(rdbCR7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbLOL)
                    .addComponent(rdbMATEMATICA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbSUPERNATURAL)
                    .addComponent(rdbNARUTO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIniciarQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCSActionPerformed

    private void rdbCR7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCR7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCR7ActionPerformed

    private void btnIniciarQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarQuizActionPerformed
        String quiz = null;
        
        if(rdbCR7.isSelected()){
            quiz = "CR7";
            } else if(rdbCS.isSelected()){
                quiz = "CS";
                } else if(rdbLOL.isSelected()){
                    quiz = "LOL";
                    } else if(rdbMATEMATICA.isSelected()){
                        quiz = "MATEMATICA";
                        } else if(rdbNARUTO.isSelected()){
                            quiz = "NARUTO";
                            } else if(rdbSUPERNATURAL.isSelected()){
                                quiz = "SUPERNATURAL";
                                } else {
                                    JOptionPane.showMessageDialog(null, "Selecione um quiz para iniciar!");
                                }
        QuizForm qf = new QuizForm(quiz);
        qf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciarQuizActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarQuiz;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rdbCR7;
    private javax.swing.JRadioButton rdbCS;
    private javax.swing.JRadioButton rdbLOL;
    private javax.swing.JRadioButton rdbMATEMATICA;
    private javax.swing.JRadioButton rdbNARUTO;
    private javax.swing.JRadioButton rdbSUPERNATURAL;
    // End of variables declaration//GEN-END:variables
}
