/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.QuizControl;
import Model.User;
import javax.swing.JOptionPane;


/**
 *
 * @author T-Gamer
 */
public class QuizForm extends javax.swing.JFrame {
    QuizControl qc;
    User u;
    int aux = 0;
    public QuizForm(String quiz) {
        initComponents();
        qc = new QuizControl(quiz);
        buildQuiz();
    }

    public void buildQuiz(){

        if (qc.getPerguntaAtual() <= 7){
            txtPergunta.setText(qc.getPerguntas());

            rdbq1.setText(qc.getAlternativas(0));
            rdbq2.setText(qc.getAlternativas(1));
            rdbq3.setText(qc.getAlternativas(2));
            rdbq4.setText(qc.getAlternativas(3));
            
        } else {
            this.dispose();
            JOptionPane.showMessageDialog(null, "Parabéns por concluir o Quiz!");
            HomeForm hf = new HomeForm();
            hf.setVisible(true);
        }
        
    }
    
    public void responder(){
        /*if (rdbq1.isSelected() == true){
                aux = 0;
                int correta = qc.getCorreta();
                
                if (correta == aux){
                    u.addScore();
                    Integer pontos = u.getScore();
                    txtScore.setText(pontos.toString());  
                }
            } else if (rdbq2.isSelected() == true){
                aux = 1;
                int correta = qc.getCorreta();
                
                if (correta == aux){
                    u.addScore();
                    Integer pontos = u.getScore();
                    txtScore.setText(pontos.toString());  
                }
            } else if (rdbq3.isSelected() == true){
                aux = 2;
                int correta = qc.getCorreta();
                
                if (correta == aux){
                    u.addScore();
                    Integer pontos = u.getScore();
                    txtScore.setText(pontos.toString());  
                }
            } else if (rdbq4.isSelected() == true){
                aux = 3;
                int correta = qc.getCorreta();
                //JOptionPane.showMessageDialog(null,"" + aux + " " + correta);
                if (correta == aux){
                    u.addScore();
                    Integer pontos = u.getScore();
                    txtScore.setText(pontos.toString());  
                }
            }*/
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblPergunta = new javax.swing.JLabel();
        lblPergunta1 = new javax.swing.JLabel();
        rdbq1 = new javax.swing.JRadioButton();
        rdbq2 = new javax.swing.JRadioButton();
        rdbq3 = new javax.swing.JRadioButton();
        rdbq4 = new javax.swing.JRadioButton();
        btnProx = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPergunta = new javax.swing.JTextArea();
        txtScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblPergunta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPergunta.setText("Pergunta:");

        lblPergunta1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPergunta1.setText("Selecione uma afirmativa:");

        buttonGroup2.add(rdbq1);
        rdbq1.setText("jRadioButton1");
        rdbq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbq1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbq2);
        rdbq2.setText("jRadioButton1");
        rdbq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbq2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbq3);
        rdbq3.setText("jRadioButton1");
        rdbq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbq3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbq4);
        rdbq4.setText("jRadioButton1");
        rdbq4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbq4ActionPerformed(evt);
            }
        });

        btnProx.setText("Próxima");
        btnProx.setEnabled(false);
        btnProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxActionPerformed(evt);
            }
        });

        txtPergunta.setEditable(false);
        txtPergunta.setColumns(20);
        txtPergunta.setRows(5);
        txtPergunta.setMaximumSize(new java.awt.Dimension(495, 50));
        txtPergunta.setMinimumSize(new java.awt.Dimension(495, 50));
        jScrollPane1.setViewportView(txtPergunta);

        txtScore.setText("Pontos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProx, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdbq4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbq3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbq2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbq1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPergunta1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblPergunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPergunta)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPergunta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbq1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbq2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbq3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbq4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtScore, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxActionPerformed
        qc.proxPergunta();
        buildQuiz(); 
        btnProx.setEnabled(false);
    }//GEN-LAST:event_btnProxActionPerformed

    private void rdbq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbq1ActionPerformed
        btnProx.setEnabled(true);
        responder();
    }//GEN-LAST:event_rdbq1ActionPerformed

    private void rdbq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbq2ActionPerformed
        btnProx.setEnabled(true);
        responder();
    }//GEN-LAST:event_rdbq2ActionPerformed

    private void rdbq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbq3ActionPerformed
        btnProx.setEnabled(true);
        responder();
    }//GEN-LAST:event_rdbq3ActionPerformed

    private void rdbq4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbq4ActionPerformed
        btnProx.setEnabled(true);
        responder();
    }//GEN-LAST:event_rdbq4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProx;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JLabel lblPergunta1;
    private javax.swing.JRadioButton rdbq1;
    private javax.swing.JRadioButton rdbq2;
    private javax.swing.JRadioButton rdbq3;
    private javax.swing.JRadioButton rdbq4;
    private javax.swing.JTextArea txtPergunta;
    private javax.swing.JLabel txtScore;
    // End of variables declaration//GEN-END:variables
}
